apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: harpangell-cert
spec:
  domains:
    - ropsten.harpangell.com
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: harpangell-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: harpangell-cert
    kubernetes.io/ingress.global-static-ip-name: harpangell-ip
spec:
  tls:
  - hosts:
    - ropsten.harpangell.com
  backend:
    serviceName: node1-public
    servicePort: 8501
