# cloudbuild.yaml
steps:
# PREPARE
- name: gcr.io/cloud-builders/gke-deploy
  id: Prepare
  args:
    - prepare
    - '--filename=clouddeploy.yaml'
    - '--image=gcr.io/harp-angell-utils/node1'
    - '--app=node1'
    - '--version=latest'
    - '--namespace=default'
    - '--output=output'
- name: gcr.io/cloud-builders/gke-deploy
  id: Deploy
  args:
    - apply
    - '--filename=output/expanded'
    - '--cluster=ethereum-cluster'
    - '--location=us-central1-c'
    - '--namespace=default'
tags:
  - gcp-cloud-build-deploy
  - node1
timeout: 900s
