version: '3.4'
# --ws --wsaddr "localhost" --wsapi "eth,web3,personal,net" --wsorigins "*"
# --gasprice 0
services:
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   container_name: nginx
  #   # restart: always
  #   ports:
  #     - 80:8501
  #   links:
  #     - node1:node1
  node1:
    build:
      context: ./nodes/node1
      dockerfile: Dockerfile
    container_name: geth-node1
    ports:
      - "8501:8501"
      - "30311:30311"
  # Uncomment if you need to persist the data on disk
    volumes:
      - ./nodes/node1/keystore:/home/ethereum/keystore
      - ./nodes/node1/geth:/home/ethereum/geth
      - ./nodes/node1/pwd/password.txt:/home/ethereum/pwd/password.txt:ro
    command: >
      geth --datadir /home/ethereum --syncmode 'full' --port 30311
      --rpc --rpcaddr '0.0.0.0' --rpcport 8501 --rpccorsdomain '*' --rpcvhosts '*'
      --rpcapi 'eth,web3,personal,net'
      --networkid 32414
      --unlock 0
      --miner.gasprice 0
      --password pwd/password.txt
      --mine --allow-insecure-unlock --nodiscover
  node2:
    build:
      context: ./nodes/node2
      dockerfile: Dockerfile
    container_name: geth-node2
    ports:
      - "8502:8502"
      - "30312:30312"
    # Uncomment if you need to persist the data on disk
    volumes:
      - ./nodes/node2/keystore:/home/ethereum/keystore
      - ./nodes/node2/geth:/home/ethereum/geth
      - ./nodes/node2/pwd/password.txt:/home/ethereum/pwd/password.txt:ro
    command: >
      geth --datadir /home/ethereum --syncmode 'full' --port 30312
      --rpc --rpcaddr '0.0.0.0' --rpcapi 'eth,web3,personal,net' --rpcport 8502 --rpccorsdomain '*' --rpcvhosts '*'
      --networkid 32414
      --unlock 0
      --miner.gasprice 0
      --password pwd/password.txt
      --mine --allow-insecure-unlock --nodiscover
  dashboard:
    build:
      context: ./monitoring/dashboard
      dockerfile: Dockerfile
    container_name: dashboard
    environment:
      - WS_SECRET=eth-net-stats-secret
    ports:
      - "3000:3000"
  ethnet:
    build:
      context: ./monitoring/api
      dockerfile: Dockerfile
    links:
      - dashboard
    container_name: ethnet
    volumes:
      - ./monitoring/api/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json
