FROM ethereum/client-go

WORKDIR /home/ethereum

# COPY static-nodes.json* /home/ethereum/
COPY pwd /home/ethereum/pwd
COPY keystore /home/ethereum/keystore
COPY geth /home/ethereum/geth

ENTRYPOINT []

EXPOSE 8502 30312 30312/udp
